spring:
  application: 
    name: TransactionService
  cloud:
    config:
      failFast: true
  config:
    import: optional:configserver:http://localhost:1111

server:
  port: 8200

management:
  endpoints:
    web:
      exposure:
        include: "*"