spring:
  application: 
    name: UserService
  cloud:
    config:
      failFast: true
      enabled: false
      import-check:
        enabled: false
  config:
    import: configserver:http://localhost:1111

server:
  port: 8400

management:
  endpoints:
    web:
      exposure:
        include: "*"