eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka, http://localhost:2223/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    hostname: Eur3
spring:
  profiles: Eureka3
  application:
    name: Eureka3
server:
  port: '2224'